org.gradle.jvmargs=-Xmx768m -Xms256m -Xss512k -XX:MaxMetaspaceSize=384m -XX:+UseG1GC -XX:ReservedCodeCacheSize=128m -XX:HeapBaseMinAddress=1G
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
kotlin.daemon.jvm.options=-Xmx256m
android.useAndroidX=true
android.enableJetifier=false
android.suppressUnsupportedOptionWarnings=android.enableJetifier
