import { Switch, Route, Redirect } from "wouter";
import AdminLayout from "@/pages/admin/layout";
import Dashboard from "@/pages/admin/dashboard";
import Trips from "@/pages/admin/trips";
import Customers from "@/pages/admin/customers";
import Drivers from "@/pages/admin/drivers";
import VehicleCategories from "@/pages/admin/vehicle-categories";
import Zones from "@/pages/admin/zones";
import Fares from "@/pages/admin/fares";
import Transactions from "@/pages/admin/transactions";
import Coupons from "@/pages/admin/coupons";
import Reviews from "@/pages/admin/reviews";
import Settings from "@/pages/admin/settings";
import BlogsPage from "@/pages/admin/blogs";
import Withdrawals from "@/pages/admin/withdrawals";
import CancellationReasonsPage from "@/pages/admin/cancellation-reasons";
import HeatMap from "@/pages/admin/heat-map";
import FleetView from "@/pages/admin/fleet-view";
import CarSharing from "@/pages/admin/car-sharing";
import IntercityCarSharing from "@/pages/admin/intercity-carsharing";
import ParcelRefunds from "@/pages/admin/parcel-refunds";
import SafetyAlerts from "@/pages/admin/safety-alerts";
import Banners from "@/pages/admin/banners";
import Discounts from "@/pages/admin/discounts";
import SpinWheel from "@/pages/admin/spin-wheel";
import Notifications from "@/pages/admin/notifications";
import DriverLevels from "@/pages/admin/driver-levels";
import CustomerLevels from "@/pages/admin/customer-levels";
import CustomerWallet from "@/pages/admin/customer-wallet";
import WalletBonus from "@/pages/admin/wallet-bonus";
import Employees from "@/pages/admin/employees";
import Newsletter from "@/pages/admin/newsletter";
import Subscriptions from "@/pages/admin/subscriptions";
import RevenueModel from "@/pages/admin/revenue-model";
import DriverWalletPage from "@/pages/admin/driver-wallet";
import RefundRequestsPage from "@/pages/admin/refund-requests";
import ApiDocsPage from "@/pages/admin/api-docs";
import AppDesignPage from "@/pages/admin/app-design";
import LanguagesPage from "@/pages/admin/languages";
import ServiceManagement from "@/pages/admin/service-management";
import ParcelAttributes from "@/pages/admin/parcel-attributes";
import VehicleAttributes from "@/pages/admin/vehicle-attributes";
import VehicleRequests from "@/pages/admin/vehicle-requests";
import ParcelFares from "@/pages/admin/parcel-fares";
import SurgePricing from "@/pages/admin/surge-pricing";
import Reports from "@/pages/admin/reports";
import Chatting from "@/pages/admin/chatting";
import CallLogs from "@/pages/admin/call-logs";
import BusinessSetup from "@/pages/admin/business-setup";
import PagesMedia from "@/pages/admin/pages-media";
import Configurations from "@/pages/admin/configurations";
import B2BCompanies from "@/pages/admin/b2b-companies";
import IntercityRoutes from "@/pages/admin/intercity-routes";
import Insurance from "@/pages/admin/insurance";
import DriverEarnings from "@/pages/admin/driver-earnings";
import Referrals from "@/pages/admin/referrals";
import DriverVerificationPage from "@/pages/admin/driver-verification";
import OutstationPool from "@/pages/admin/outstation-pool";
import LocalPool from "@/pages/admin/local-pool";
import ParcelOrders from "@/pages/admin/parcel-orders";
import SystemHealth from "@/pages/admin/system-health";
import VoiceCommandsPage from "@/pages/admin/voice-commands";
import PopularLocationsAdmin from "@/pages/admin/popular-locations";
import CityServices from "@/pages/admin/city-services";
import ParcelVehiclesAdmin from "@/pages/admin/parcel-vehicles";
import AIBrainDashboard from "@/pages/admin/ai-brain-dashboard";

export default function AdminRoutes() {
  return (
    <AdminLayout>
      <Switch>
        <Route path="/admin/dashboard" component={Dashboard} />
        <Route path="/admin/heat-map" component={HeatMap} />
        <Route path="/admin/fleet-view" component={FleetView} />
        <Route path="/admin/zones" component={Zones} />
        <Route path="/admin/trips" component={Trips} />
        <Route path="/admin/car-sharing" component={CarSharing} />
        <Route path="/admin/intercity-carsharing" component={IntercityCarSharing} />
        <Route path="/admin/outstation-pool" component={OutstationPool} />
        <Route path="/admin/local-pool" component={LocalPool} />
        <Route path="/admin/parcel-refunds" component={ParcelRefunds} />
        <Route path="/admin/safety-alerts" component={SafetyAlerts} />
        <Route path="/admin/banners" component={Banners} />
        <Route path="/admin/coupons" component={Coupons} />
        <Route path="/admin/discounts" component={Discounts} />
        <Route path="/admin/spin-wheel" component={SpinWheel} />
        <Route path="/admin/notifications" component={Notifications} />
        <Route path="/admin/driver-levels" component={DriverLevels} />
        <Route path="/admin/driver-verification" component={DriverVerificationPage} />
        <Route path="/admin/drivers" component={Drivers} />
        <Route path="/admin/withdrawals" component={Withdrawals} />
        <Route path="/admin/customer-levels" component={CustomerLevels} />
        <Route path="/admin/customers" component={Customers} />
        <Route path="/admin/customer-wallet" component={CustomerWallet} />
        <Route path="/admin/wallet-bonus" component={WalletBonus} />
        <Route path="/admin/employees" component={Employees} />
        <Route path="/admin/newsletter" component={Newsletter} />
        <Route path="/admin/subscriptions" component={Subscriptions} />
        <Route path="/admin/revenue-model" component={RevenueModel} />
        <Route path="/admin/parcel-attributes" component={ParcelAttributes} />
        <Route path="/admin/vehicle-attributes" component={VehicleAttributes} />
        <Route path="/admin/vehicles" component={VehicleCategories} />
        <Route path="/admin/vehicle-requests" component={VehicleRequests} />
        <Route path="/admin/fares" component={Fares} />
        <Route path="/admin/cancellation-reasons" component={CancellationReasonsPage} />
        <Route path="/admin/parcel-fares" component={ParcelFares} />
        <Route path="/admin/surge-pricing" component={SurgePricing} />
        <Route path="/admin/transactions" component={Transactions} />
        <Route path="/admin/reports" component={Reports} />
        <Route path="/admin/chatting" component={Chatting} />
        <Route path="/admin/call-logs" component={CallLogs} />
        <Route path="/admin/blogs" component={BlogsPage} />
        <Route path="/admin/reviews" component={Reviews} />
        <Route path="/admin/business-setup" component={BusinessSetup} />
        <Route path="/admin/pages-media" component={PagesMedia} />
        <Route path="/admin/configurations" component={Configurations} />
        <Route path="/admin/settings" component={Settings} />
        <Route path="/admin/b2b-companies" component={B2BCompanies} />
        <Route path="/admin/intercity-routes" component={IntercityRoutes} />
        <Route path="/admin/insurance" component={Insurance} />
        <Route path="/admin/driver-earnings" component={DriverEarnings} />
        <Route path="/admin/driver-wallet" component={DriverWalletPage} />
        <Route path="/admin/refund-requests" component={RefundRequestsPage} />
        <Route path="/admin/api-docs" component={ApiDocsPage} />
        <Route path="/admin/app-design" component={AppDesignPage} />
        <Route path="/admin/languages" component={LanguagesPage} />
        <Route path="/admin/service-management" component={ServiceManagement} />
        <Route path="/admin/parcel-orders" component={ParcelOrders} />
        <Route path="/admin/system-health" component={SystemHealth} />
        <Route path="/admin/voice-commands" component={VoiceCommandsPage} />
        <Route path="/admin/referrals" component={Referrals} />
        <Route path="/admin/popular-locations" component={PopularLocationsAdmin} />
        <Route path="/admin/city-services" component={CityServices} />
        <Route path="/admin/parcel-vehicle-types" component={ParcelVehiclesAdmin} />
        <Route path="/admin/ai-brain" component={AIBrainDashboard} />
        <Route><Redirect to="/admin/dashboard" /></Route>
      </Switch>
    </AdminLayout>
  );
}
